Repository swagger-api/swagger-js, pull requests merged in 2020-10, with the labels that each got.

#1737 chore(release): fix release script
  release/get-changelog.sh
Labels: cat: documentation, version: 3.x

#1738 Eliminate examples directory #1733
  examples/all-of.js
  examples/oas3.js
  examples/quick.js
  examples/ref.js
Labels: Hacktoberfest, cat: documentation, cat: usability, version: 3.x

#1739 Remove engines field from package.json #1684
  docs/development/setting-up.md
  package.json
Labels: Hacktoberfest, cat: usability, version: 3.x

#1741 fix: Installation documentation #1740
  docs/usage/installation.md
Labels: cat: documentation, type: enhancement, version: 3.x

#1748 #1724 update subtree resolver test to be more inclusive
  test/subtree-resolver.js
Labels: Hacktoberfest, cat: testing, type: enhancement, version: 3.x

#1773 chore(deps-dev): bump webpack-cli from 4.0.0 to 4.1.0
  package-lock.json
  package.json
Labels: dependencies

#1778 ci: automerge dependabot PRs that passes CI
  .github/workflows/nodejs.yml
Labels: dependencies, type: enhancement, version: 3.x

#1779 ci(GA): use swagger-bot token
  .github/workflows/nodejs.yml
Labels: dependencies, type: enhancement, version: 3.x

#1783 fix(resolver): bail out from all-off plugin prematurely
  package-lock.json
  package.json
  src/specmap/lib/all-of.js
  test/specmap/all-of.js
Labels: cat: usability, dependencies, type: bug, version: 3.x
