Repository swagger-api/swagger-js, pull requests merged in 2020-11, with the labels that each got.

#1807 chore(prettier): remove redundant YAML config
  .prettierrc.yaml
  test/build-artifacts/es.js
Labels: type: enhancement

#1817 chore(dev-deps): update prettier to v2.2.0
  package-lock.json
  package.json
  src/execute/index.js
Labels: dependencies, version: 3.x

#1810 fix(specmap): Do not resolve $refs in most example values
  src/specmap/lib/refs.js
  test/bugs/ui-4924.js
  test/data/parameter-examples-with-refs.yaml
  test/specmap/refs.js
Labels: cat: usability, type: enhancement, version: 3.x
