Repository swagger-api/swagger-js, pull requests merged in 2020-07, with the labels that each got.

#1621 chore(security): allow whitlists for npm audit
  .npmrc
  docs/development/scripts.md
  package-lock.json
  package.json
  scripts/.eslintrc
  scripts/npm-audit.js
Labels: CICD, cat: security, cat: testing, dependencies, version: 3.x

#1620 installation.md - some fixes to html code (missing tags, fixed url)
  docs/usage/installation.md
Labels: cat: documentation, cat: usability, version: 3.x

#1619 docs(tags-interface): add section about overrides
  docs/usage/tags-interface.md
Labels: cat: documentation, cat: usability, version: 3.x

#1623 docs: remove obsolete file pointers
  docs/GRAVEYARD.md
  docs/MIGRATION_2_X.md
Labels: cat: documentation, version: 2.x, version: 3.x

#1624 ci(npm-audit): make npm audit output on failure only
  .github/workflows/nodejs.yml
  scripts/npm-audit.js
Labels: CICD, dependencies, version: 3.x

#1625 build(package): remove browser field
  package.json
Labels: cat: usability, type: enhancement, version: 3.x

#1626 build(babel): decrease size of ES5 build fragment
  .babelrc
  package-lock.json
  package.json
Labels: cat: usability, dependencies, type: enhancement, version: 3.x

#1629 fix(resolver): support legacy fetch override as an alias of http
  docs/usage/openapi-definition-resolver.md
  src/index.js
Labels: type: bug, version: 3.x

#1630 docs(setting-up): add section about linking swagger-js and swagger-ui
  docs/development/setting-up.md
Labels: cat: documentation, version: 3.x

#1622 docs(README): add compatibility table for OAS versions
  README.md
Labels: cat: documentation, version: 2.x, version: 3.x

#1631 fix(build): add eplixit helpers support
  .babelrc
  package-lock.json
  package.json
  src/commonjs.js
  src/index.js
  test/build-artifacts/commonjs.js
Labels: type: regression, version: 3.x

#1640 Inject missing ponyfills for `cross-fetch` in UMD build
  .babelrc
  babel.config.js
  config/webpack/browser.config.babel.js
  test/build-artifacts/umd.js
Labels: cat: usability, dependencies, type: enhancement, version: 3.x

#1650 chore(deps): update dependencies to latest versions
  package-lock.json
  package.json
Labels: dependencies, version: 3.x

#1657 chore(ci): add npm audit check right after install
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
  scripts/.eslintrc
  scripts/npm-audit.js
Labels: CICD, cat: security, version: 3.x
