Repository swagger-api/swagger-js, pull requests merged in 2021-02, with the labels that each got.

#1883 feat: Support relative server url for OAS3
  src/execute/index.js
  test/oas3/execute/main.js
Labels: type: enhancement, version: 3.x

#1909 chore(husky): migrate configuration to v5
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  .huskyrc
  package.json
Labels: type: enhancement, version: 3.x

#1912 fix(husky): remove postinstall script
  package.json
Labels: type: bug, version: 3.x

#1913 chore(husky): run hooks with npx
  .husky/commit-msg
  .husky/pre-commit
Labels: dependencies, type: enhancement, version: 3.x
