Repository swagger-api/swagger-js, pull requests merged in 2021-03, with the labels that each got.

#1982 ci(GA): allow dependabot PRs merge
  .github/workflows/dependabot-merge.yml
  .github/workflows/nodejs.yml
Labels: cat: security, type: enhancement

#1987 ci(dependabot): wait for status check before merge
  .github/workflows/dependabot-merge.yml
Labels: CICD

#1988 ci(dependabot): switch merge GA
  .github/workflows/dependabot-merge.yml
Labels: CICD

#1981 Set accept header according to the the produces content-types defined in the API
  src/execute/oas3/build-request.js
  src/execute/swagger2/build-request.js
  test/execute/main.js
  test/oas3/execute/build-request.js
  test/swagger2/execute/build-request.js
Labels: type: bug, version: 3.x
