Repository swagger-api/swagger-js, pull requests merged in 2023-07, with the labels that each got.

#3001 test: remove duplicated code
  test/oas3/execute/main.js
Labels: version: 3.x, type: enhancement

#3051 chore(deps-dev): bump prettier from 2.8.8 to 3.0.0
  package-lock.json
  package.json
Labels: version: 3.x, dependencies

#3050 fix(resolve): fix critial bug in OpenAPI 3.1.0 resolution
  package-lock.json
  package.json
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/path-item-object/dereference-apidom.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/dereference-apidom.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$anchor-internal-no-embedding/dereferenced.json
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$anchor-internal-no-embedding/root.json
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$ref-url-path-override/dereferenced.json
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/__fixtures__/$ref-url-path-override/root.json
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/dereference-apidom.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/index.js
Labels: type: bug, version: 3.x
