Repository swagger-api/swagger-js, pull requests merged in 2023-03, with the labels that each got.

#2861 feat(deps): use ApiDOM npmjs.com npm packages
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  .npmrc
  docs/development/setting-up.md
  docs/usage/installation.md
  package-lock.json
  package.json
Labels: version: 3.x, type: enhancement, dependencies

#2868 chore(deps-dev): bump glob from 8.1.0 to 9.2.1
  package-lock.json
  package.json
  test/specmap/complex.js
  test/specmap/refs.js
Labels: dependencies

#2869 ci(release): re-enable automatic CICD pipeline
  .github/workflows/release.yml
  .releaserc
Labels: type: enhancement, CICD

#2844 fix(http): Handle undefined serialized JSON Query param
  src/execute/oas3/parameter-builders.js
  test/client.js
  test/data/sample-query-parameter-json.yaml
Labels: type: bug, version: 3.x

#2886 fix: use forward compatible OpenAPI version detection
  src/helpers/openapi-predicates.js
Labels: type: enhancement

#2901 fix(deps): update ApiDOM to v0.69.1
  package-lock.json
  package.json
Labels: type: enhancement, dependencies
