Repository swagger-api/swagger-js, pull requests merged in 2024-04, with the labels that each got.

#3456 fix(resolver): fix side effects in OpenAPI 3.1.0 resolving
  package-lock.json
  package.json
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/index.js
Labels: type: bug, version: 3.x, cat: resolver

#3446 fix(execute): fix encoding of complex nested type values in OpenAPI 3.x request builders
  src/execute/oas3/style-serializer.js
  src/http/index.js
  test/oas3/execute/main.js
Labels: type: bug, version: 3.x

#3463 fix(execute): refactor encodeDisallowedCharacters function
  src/execute/oas3/parameter-builders.js
  src/execute/oas3/style-serializer.js
  test/oas3/execute/style-serializer.js
Labels: type: bug, version: 3.x

#3466 fix(execute): parse stringified objects nested in arrays
  src/execute/oas3/content-serializer.js
  test/oas3/execute/main.js
Labels: type: bug, version: 3.x

#3473 chore(deps-dev): update unidici to non-vulnerable v5.28.4
  package-lock.json
  package.json
Labels: cat: security, dependencies

#3479 chore(deps): pin traverse to v0.6.8
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: type: regression, version: 3.x, type: enhancement, dependencies

#3474 fix(execute): parse stringified objects
  src/http/index.js
  test/oas3/execute/main.js
Labels: type: bug, version: 3.x

#3476 fix(execute): fix encoding for stringified request body
  src/http/index.js
  test/oas3/execute/main.js
Labels: type: bug, version: 3.x

#3482 refactor(http): refactor http client
  src/execute/index.js
  src/execute/oas3/build-request.js
  src/http/index.js
  src/http/serializers/request/file.js
  src/http/serializers/request/format.js
  src/http/serializers/request/index.js
  src/http/serializers/response/index.js
  src/index.js
  test/http/index.js
Labels: type: enhancement

#3484 ci(dependabot): ignore semver-major updates for unidic@5
  .github/dependabot.yml
Labels: dependencies, CICD

#3486 refactor(specmap): move specmap implementation to resolve module
  config/jest/jest.unit.config.js
  src/execute/index.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/errors/index.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
  src/resolver/specmap/helpers.js
  src/resolver/specmap/index.js
  src/resolver/specmap/lib/all-of.js
  src/resolver/specmap/lib/context-tree.js
  src/resolver/specmap/lib/create-error.js
  src/resolver/specmap/lib/index.js
  src/resolver/specmap/lib/parameters.js
  src/resolver/specmap/lib/properties.js
  src/resolver/specmap/lib/refs.js
  src/resolver/strategies/generic/index.js
  src/resolver/strategies/generic/resolve.js
  test/resolver/specmap/all-of.js
  test/resolver/specmap/complex.js
  test/resolver/specmap/context-tree.js
  test/resolver/specmap/data/complex/complex-example.json
  test/resolver/specmap/data/cyclic/external/1.js
  test/resolver/specmap/data/cyclic/external/10.js
  test/resolver/specmap/data/cyclic/external/2.js
  test/resolver/specmap/data/cyclic/external/20.js
  test/resolver/specmap/data/cyclic/external/21.js
  test/resolver/specmap/data/cyclic/external/30.js
  test/resolver/specmap/data/cyclic/external/31.js
  test/resolver/specmap/data/cyclic/external/32.js
  test/resolver/specmap/data/cyclic/external/40.js
  test/resolver/specmap/data/cyclic/internal/1.js
  test/resolver/specmap/data/cyclic/internal/10.js
  test/resolver/specmap/data/cyclic/internal/11.js
  test/resolver/specmap/data/cyclic/internal/12.js
  test/resolver/specmap/data/cyclic/internal/2.js
  test/resolver/specmap/data/cyclic/internal/20.js
  test/resolver/specmap/data/cyclic/internal/21.js
  test/resolver/specmap/data/cyclic/internal/22.js
  test/resolver/specmap/data/cyclic/internal/3.js
  test/resolver/specmap/data/cyclic/internal/30.js
  test/resolver/specmap/data/cyclic/internal/31.js
  test/resolver/specmap/data/cyclic/internal/40.js
  test/resolver/specmap/data/cyclic/internal/41.js
  test/resolver/specmap/data/cyclic/internal/50.js
  test/resolver/specmap/data/specs/example-underten.json
  test/resolver/specmap/data/specs/example.json
  test/resolver/specmap/data/specs/example.resolved.json
  test/resolver/specmap/data/specs/petstore-simple-resolved.json
  test/resolver/specmap/data/specs/petstore-simple.json
  test/resolver/specmap/index.js
  test/resolver/specmap/lib.js
  test/resolver/specmap/live.js
  test/resolver/specmap/parameters.js
  test/resolver/specmap/properties.js
  test/resolver/specmap/refs.js
Labels: version: 3.x, cat: specmap, type: enhancement

#3487 refactor: use standard error constructor signatures
  src/execute/index.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/errors/SchemaRefError.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/errors/index.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
  src/resolver/specmap/lib/create-error.js
  src/resolver/specmap/lib/refs.js
Labels: version: 3.x, type: enhancement
