Repository swagger-api/swagger-js, pull requests merged in 2024-12, with the labels that each got.

#3726 fix(execute): fix encoding of object properties with null value
  src/execute/oas3/style-serializer.js
  src/http/serializers/request/index.js
  test/oas3/execute/main.js
Labels: type: bug, version: 3.x

#3751 fix(execute): align Path Templates processing with OpenAPI spec
  package-lock.json
  package.json
Labels: version: 3.x, type: enhancement, dependencies

#3752 fix(execute): apply fix for faulty OpenAPI Path Templating ABNF
  package-lock.json
  package.json
Labels: type: regression, version: 3.x, dependencies

#3754 feat: add support for OpenAPI 3.0.4
  README.md
  docs/usage/http-client-for-oas-operations.md
  package-lock.json
  package.json
  src/helpers/openapi-predicates.js
  src/subtree-resolver/index.js
  test/bugs/ui-4071.js
  test/data/issue-1719-ref-object-reference.yaml
  test/data/parameter-examples-with-refs.yaml
  test/data/relative-server.openapi.yaml
  test/data/sample-multipart-oas3.js
  test/data/sample-query-parameter-json.yaml
  test/execute/server-variable-encoder.js
  test/helpers/openapi-predicates.js
  test/http/http-multipart.js
  test/index.js
  test/oas3/data/petstore-oas3.yaml
  test/oas3/execute/authorization.js
  test/oas3/execute/build-request.js
  test/oas3/execute/main.js
  test/oas3/execute/style-explode/cookie.js
  test/oas3/execute/style-explode/header.js
  test/oas3/execute/style-explode/path.js
  test/oas3/execute/style-explode/query.js
  test/resolver/circular-references-instantiation.yaml
  test/resolver/circular-references-subtree-resolver.yaml
  test/resolver/strategies/generic/index.js
  test/resolver/swos-109-instantiation.yaml
  test/resolver/swos-109-subtree-resolver.yaml
Labels: type: feature, version: 3.x, cat: resolver
