Repository swagger-api/swagger-js, pull requests merged in 2024-02, with the labels that each got.

#3367 fix(execute): empty field added to multi-value parameters
  src/execute/oas3/parameter-builders.js
  test/execute/openapi-3-1.js
Labels: type: bug

#3383 fix(security): fix proxy-Authorization header security issue
  README.md
  package-lock.json
  package.json
  src/helpers/fetch-polyfill.node.js
  src/helpers/fetch-ponyfill-undici.node.js
  test/jest.setup.js
Labels: version: 3.x, cat: security, security vulnerability, security fix

#3380 fix(specmap): limit depth of traversal
  src/specmap/index.js
  test/specmap/complex.js
  test/specmap/data/complex/complex-example.json
Labels: type: bug, cat: specmap
