Repository swagger-api/swagger-js, pull requests merged in 2024-11, with the labels that each got.

#3707 feat(analytics): use Scarf.js to provide anonymized installation analytics
  README.md
  package-lock.json
  package.json
Labels: version: 3.x, cat: usability, dependencies

#3708 fix: README md typo around scafe/scarf
  README.md
Labels: cat: documentation, type: enhancement

#3709 chore(deps): update Scarf.js to v1.4.0
  package-lock.json
  package.json
Labels: type: enhancement, dependencies

#3720 chore: use Node.js 22 for dev env
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  .nvmrc
  docs/development/setting-up.md
Labels: version: 3.x, type: enhancement, dependencies

#3722 feat: use ApiDOM@1.0.0-beta.x
  package-lock.json
  package.json
Labels: type: enhancement, dependencies

#3723 fix: use ApiDOM@1.0.0-beta.3 with fixed deps chain
  package-lock.json
  package.json
Labels: type: integration bug, version: 3.x, dependencies
