Repository swagger-api/swagger-js, pull requests merged in 2024-03, with the labels that each got.

#3399 fix(specmap): change traversal limit logic
  src/specmap/index.js
  test/specmap/complex.js
Labels: type: bug, type: regression, version: 3.x, cat: specmap

#3403 feat(resolver): adapt OpenAPI 3.1.0 resolver startegy with ApiDOM@0.97.0
  package-lock.json
  package.json
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
Labels: version: 3.x, type: enhancement

#3431 chore: bump ApiDOM to v0.98.0
  package-lock.json
  package.json
  src/resolver/strategies/openapi-3-1-apidom/resolve.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/__utils__/jest.local.setup.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/index.js
Labels: cat: testing, dependencies

#3432 fix(execute): skip undefined values serialization
  src/execute/oas3/parameter-builders.js
  test/oas3/execute/main.js
Labels: type: bug

#3435 fix(execute): add falsy formData values to requests
  src/execute/swagger2/parameter-builders.js
  test/execute/main.js
Labels: type: bug, version: 2.x

#3437 fix(execute): align form data builder with query builder behaviour
  src/execute/swagger2/parameter-builders.js
  test/execute/main.js
Labels: type: bug, version: 2.x

#3439 fix(execute): skip undefined parameters in body and path request builders for OpenAPI 2.0
  src/execute/swagger2/parameter-builders.js
  test/execute/main.js
Labels: type: bug, version: 2.x
