Repository swagger-api/swagger-js, pull requests merged in 2024-05, with the labels that each got.

#3504 fix(security): replace regular expressions in path builders
  config/webpack/browser.config.babel.js
  package-lock.json
  package.json
  src/execute/index.js
  src/execute/oas3/parameter-builders.js
  src/execute/swagger2/parameter-builders.js
Labels: version: 3.x, cat: security

#3502 fix(security): fix polynomial regular expression
  src/execute/index.js
Labels: type: bug, version: 3.x, cat: security, security fix

#3507 fix(security): remedy polynomial regular expression without limiting length to 29 chars
  src/execute/index.js
Labels: version: 3.x, cat: security

#3511 fix(execute): resolve multiple path parameters with the same name in path templates
  src/execute/index.js
  src/execute/oas3/parameter-builders.js
  src/execute/swagger2/parameter-builders.js
  test/execute/main.js
Labels: type: regression, version: 3.x

#3513 fix(deps): allow to consolidate deps in downstream projects
  package-lock.json
  package.json
Labels: type: enhancement, dependencies

#3517 ci: use advanced CodeQL analysis
  .github/workflows/codeql.yml
Labels: version: 3.x, type: enhancement, CICD

#3519 feat: integrate ApiDOM@1.0.0
  .eslintrc
  .eslintrc.js
  config/jest/jest.unit.config.js
  config/jest/jest.unit.coverage.config.js
  package-lock.json
  package.json
  src/index.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/index.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/utils/compose.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/all-of.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/parameters.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/properties.js
  src/resolver/apidom/reference/parse/parsers/json/index.js
  src/resolver/apidom/reference/parse/parsers/openapi-json-3-1/index.js
  src/resolver/apidom/reference/parse/parsers/openapi-yaml-3-1/index.js
  src/resolver/apidom/reference/parse/parsers/yaml-1-2/index.js
  src/resolver/apidom/reference/resolve/resolvers/http-swagger-client/index.js
  src/resolver/strategies/openapi-3-1-apidom/resolve.js
  test/.eslintrc
  test/.eslintrc.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/__utils__/jest.local.setup.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/path-item-object/index.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/reference-object/index.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/all-of.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/dereference-apidom.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/index.js
  test/resolver/apidom/reference/parse/parsers/json/index.js
  test/resolver/apidom/reference/parse/parsers/openapi-json-3-1/index.js
  test/resolver/apidom/reference/parse/parsers/openapi-yaml-3-1/index.js
  test/resolver/apidom/reference/parse/parsers/yaml-1-2/index.js
  test/resolver/apidom/reference/resolve/resolvers/http-swagger-client/index.js
  test/resolver/strategies/openapi-3-1-apidom/index.js
Labels: type: enhancement, dependencies

#3521 fix(resolver): fix execution of OpenAPI 3.1.0 dereference plugins
  config/jest/jest.unit.config.js
  package-lock.json
  package.json
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/index.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/dereference.js
  src/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/visitors/root.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/parameter-object/parameter-macro.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/all-of.js
  test/resolver/apidom/reference/dereference/strategies/openapi-3-1-swagger-client/schema-object/model-property-macro.js
  test/resolver/apidom/reference/parse/parsers/openapi-yaml-3-1/index.js
  test/resolver/strategies/openapi-3-1-apidom/__fixtures__/ref-all-of-macros.json
  test/resolver/strategies/openapi-3-1-apidom/__snapshots__/index.js.snap
  test/resolver/strategies/openapi-3-1-apidom/index.js
Labels: type: regression, version: 3.x

#3540 test: integrate ApiDOM@1.0.0-alpha.4
  package-lock.json
  package.json
  test/resolver/strategies/openapi-3-1-apidom/__snapshots__/index.js.snap
  test/resolver/strategies/openapi-3-1-apidom/normalize/__snapshots__/index.js.snap
  test/subtree-resolver/strategies/openapi-3-1-apidom/__snapshots__/index.js.snap
Labels: version: 3.x, cat: testing, dependencies
